from turtle import *
ml = input("kas sa maletad oma unenagu? ")
if ml == ("jah"):
    vrv = input("mis varvi oli su unenagu? ")
    kuju = input("mis kujuga oli tegelane? ")
    ptvrv = input("mis varvi oli tegelane? ")
setup(300,300)
bgcolor(vrv)
fillcolor(ptvrv)
if kuju == ("ring"):
    circle(50,360)
elif kuju == ("ruut"):
    begin_fill()
    fd(50)
    right(90)
    fd(50)
    right(90)
    fd(50)
    right(90)
    fd(50)
    end_fill()
elif kuju == ("ristkulik"):
    begin_fill()
    fd(100)
    right(90)
    fd(50)
    right(90)
    fd(100)
    right(90)
    fd(50)
    end_fill()
elif kuju == ("kolmnurk"):
    begin_fill()
    fd(100)
    left(120)
    fd(100)
    left(120)
    fd(100)
    end_fill()
hideturtle()
exitonclick()